#!/usr/bin/env python3
"""Pass 2: reverse-geocode the imported places and generate their slugs.

Nothing in deannd's KMLs carries city, country or address -- only
coordinates. This resolves them against Nominatim and emits SQL, so the
import itself never depends on a network service and this can be re-run,
interrupted, or resumed without redoing work.

Every response is cached to disk keyed by coordinate. A second run costs
zero requests. Anything that fails to resolve is logged and left NULL --
never guessed.

    python3 scripts/geocode.py            # resume, ~35 min cold for 2,095
    python3 scripts/geocode.py --sql-only # regenerate SQL from cache, no network

Writes:
    data/geocode-cache.json          coordinate -> Nominatim address
    supabase/seed_geocode.sql        UPDATEs for city, country_code, slug
    notes/geocode-failures.log       anything unresolved
"""

import json
import os
import re
import sys
import time
import unicodedata
import urllib.error
import urllib.parse
import urllib.request
from collections import defaultdict

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DATA = os.path.join(ROOT, 'data')
CACHE_PATH = os.path.join(DATA, 'geocode-cache.json')

# Nominatim's usage policy requires a genuine identifying User-Agent and no
# more than one request per second. Both are conditions of the free service;
# breaking either gets the IP blocked, and rightly.
USER_AGENT = 'bourdain-map/0.1 (sanskardugar2001@gmail.com)'
MIN_INTERVAL = 1.0
ENDPOINT = 'https://nominatim.openstreetmap.org/reverse'

# zoom=14 asks for suburb/city granularity rather than a full street address.
# We want "San Francisco", not "1517 Polk St".
ZOOM = 14

MAX_ATTEMPTS = 3
BACKOFF = 5.0

# Nominatim's address keys vary by country -- a place can be a city, town,
# village, municipality or none of them. Most specific first.
CITY_KEYS = ['city', 'town', 'village', 'municipality', 'borough',
             'suburb', 'city_district', 'county', 'state_district', 'state']


def load_json(path, default):
    if os.path.exists(path):
        with open(path, encoding='utf-8') as f:
            return json.load(f)
    return default


def key_for(lon, lat):
    """~1m precision. Two places this close share an answer, which is correct."""
    return f'{lat:.5f},{lon:.5f}'


def fetch(lon, lat):
    """One reverse lookup. Returns the address dict, or raises."""
    url = ENDPOINT + '?' + urllib.parse.urlencode({
        'format': 'jsonv2', 'lat': f'{lat:.6f}', 'lon': f'{lon:.6f}',
        'zoom': ZOOM, 'addressdetails': 1,
    })
    req = urllib.request.Request(url, headers={
        'User-Agent': USER_AGENT,
        'Accept': 'application/json',
        'Accept-Language': 'en',
    })
    with urllib.request.urlopen(req, timeout=30) as resp:
        return json.loads(resp.read().decode('utf-8'))


def extract(payload):
    """Pull city + ISO country out of a Nominatim response."""
    if not payload or 'error' in payload:
        return None, None
    addr = payload.get('address') or {}
    city = next((addr[k] for k in CITY_KEYS if addr.get(k)), None)
    cc = addr.get('country_code')
    return city, (cc.upper() if cc else None)


# Characters NFKD does not decompose, so they survive into slugs as gaps:
# Garðabær became "gar-ab-r". Handled before the accent strip.
XLIT = str.maketrans({
    'ð': 'd', 'Ð': 'd', 'þ': 'th', 'Þ': 'th', 'æ': 'ae', 'Æ': 'ae',
    'ø': 'o', 'Ø': 'o', 'œ': 'oe', 'Œ': 'oe', 'ł': 'l', 'Ł': 'l',
    'đ': 'd', 'Đ': 'd', 'ı': 'i', 'İ': 'i', 'ß': 'ss', 'ħ': 'h',
    'ŋ': 'n', 'ə': 'e', 'Ə': 'e', 'ʻ': '', 'ʼ': '', '‘': '', '’': '',
})


def slugify(s):
    s = (s or '').translate(XLIT)
    s = unicodedata.normalize('NFKD', s)
    s = ''.join(c for c in s if not unicodedata.combining(c))
    s = s.lower().replace('&', ' and ')
    s = re.sub(r"['’]", '', s)
    s = re.sub(r'[^a-z0-9]+', '-', s)
    return re.sub(r'-+', '-', s).strip('-')


def build_slugs(places, resolved):
    """name-city, deduplicated. Places without a city get no slug at all.

    Slugs are URLs. Generating them once, here, after city is known means no
    live URL ever has to change -- which is why slug stayed nullable through
    the import rather than being invented from the name alone.
    """
    slugs, taken = {}, defaultdict(int)
    for p in sorted(places, key=lambda p: p['id']):
        city, _ = resolved.get(key_for(p['lon'], p['lat']), (None, None))
        if not city:
            continue
        base = slugify(p['name'])
        if not base:
            continue
        city_part = slugify(city)
        cand = f'{base}-{city_part}' if city_part else base
        taken[cand] += 1
        if taken[cand] > 1:
            cand = f'{cand}-{taken[cand]}'
        slugs[p['id']] = cand
    return slugs


def sql(v):
    if v is None:
        return 'NULL'
    return "'" + str(v).replace("'", "''") + "'"


def write_sql(places, resolved, slugs, path):
    out = ['-- Generated by scripts/geocode.py. Do not edit by hand.',
           '-- Reverse-geocoded from coordinates via Nominatim (OpenStreetMap).',
           '-- Places that did not resolve keep NULL city/country/slug -- see',
           '-- notes/geocode-failures.log. Nothing here is guessed.',
           '']
    n = 0
    for p in sorted(places, key=lambda p: p['id']):
        city, cc = resolved.get(key_for(p['lon'], p['lat']), (None, None))
        slug = slugs.get(p['id'])
        if not (city or cc or slug):
            continue
        out.append(
            f"update public.places set city={sql(city)}, country_code={sql(cc)}, "
            f"slug={sql(slug)} where id='{p['id']}'::uuid;")
        n += 1
    out.append('')
    with open(path, 'w', encoding='utf-8') as f:
        f.write('\n'.join(out))
    return n


def main():
    sql_only = '--sql-only' in sys.argv

    manifest = os.path.join(DATA, 'places.json')
    if not os.path.exists(manifest):
        sys.exit('data/places.json not found -- run scripts/import_kml.py first')
    places = load_json(manifest, [])
    cache = load_json(CACHE_PATH, {})

    todo = [p for p in places if key_for(p['lon'], p['lat']) not in cache]
    print(f'{len(places)} places, {len(cache)} cached, {len(todo)} to fetch')
    if todo and not sql_only:
        print(f'~{len(todo) * MIN_INTERVAL / 60:.0f} min at 1 req/sec')

    failures = []
    if not sql_only:
        last = 0.0
        for i, p in enumerate(todo, 1):
            k = key_for(p['lon'], p['lat'])
            for attempt in range(1, MAX_ATTEMPTS + 1):
                wait = MIN_INTERVAL - (time.monotonic() - last)
                if wait > 0:
                    time.sleep(wait)
                last = time.monotonic()
                try:
                    cache[k] = fetch(p['lon'], p['lat'])
                    break
                except urllib.error.HTTPError as e:
                    if e.code in (429, 503) and attempt < MAX_ATTEMPTS:
                        time.sleep(BACKOFF * attempt)
                        continue
                    failures.append(f'HTTP {e.code}  {p["name"]!r}  {k}')
                    break
                except Exception as e:                      # noqa: BLE001
                    if attempt < MAX_ATTEMPTS:
                        time.sleep(BACKOFF * attempt)
                        continue
                    failures.append(f'{type(e).__name__}: {e}  {p["name"]!r}  {k}')
                    break

            # Checkpoint often. An interrupted run must never redo work.
            if i % 25 == 0 or i == len(todo):
                with open(CACHE_PATH, 'w', encoding='utf-8') as f:
                    json.dump(cache, f, ensure_ascii=False)
                print(f'  {i}/{len(todo)}  ({len(failures)} failed)', flush=True)

        with open(CACHE_PATH, 'w', encoding='utf-8') as f:
            json.dump(cache, f, ensure_ascii=False)

    # Resolve everything we have, and record what came back unusable.
    resolved, unresolved = {}, []
    for p in places:
        k = key_for(p['lon'], p['lat'])
        if k not in cache:
            unresolved.append(f'NOT_FETCHED  {p["name"]!r}  {k}')
            continue
        city, cc = extract(cache[k])
        if not city and not cc:
            unresolved.append(f'NO_ADDRESS   {p["name"]!r}  {k}')
        elif not city:
            unresolved.append(f'NO_CITY      {p["name"]!r}  {k}  (country {cc})')
        resolved[k] = (city, cc)

    slugs = build_slugs(places, resolved)
    n = write_sql(places, resolved, slugs,
                  os.path.join(ROOT, 'supabase', 'seed_geocode.sql'))

    os.makedirs(os.path.join(ROOT, 'notes'), exist_ok=True)
    with open(os.path.join(ROOT, 'notes', 'geocode-failures.log'), 'w', encoding='utf-8') as f:
        f.write(f'{len(failures)} request failures, {len(unresolved)} unresolved.\n'
                'These keep NULL city/country/slug. Nothing is guessed.\n\n')
        f.write('\n'.join(failures + sorted(unresolved)) + '\n')

    with_city = sum(1 for v in resolved.values() if v[0])
    print(f'resolved   {with_city}/{len(places)} with a city')
    print(f'slugs      {len(slugs)}')
    print(f'updates    {n}  -> supabase/seed_geocode.sql')
    print(f'failures   {len(failures)} requests, {len(unresolved)} unresolved '
          f'-> notes/geocode-failures.log')


if __name__ == '__main__':
    main()
